# Code generated by images/scripts/update-cni-version.sh; DO NOT EDIT.
cni_version="1.4.1"
declare -A cni_sha512
cni_sha512[loong64]="5bc7985428c5825c6eaa74a92ebb60ed4669c6ccc24bff49d7df1ccd5b79a03dfcb289e4ec1310b230eb8c72bd7c1321dfe0ee76f46c067b2039dc3936f50055"
